#if !canImport(ObjectiveC)
import XCTest

extension ApplicationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApplicationTests = [
        ("testApplication", testApplication),
        ("testApplicationBasePath", testApplicationBasePath),
        ("testApplicationMiddleware", testApplicationMiddleware),
    ]
}

extension MiddlewareTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MiddlewareTests = [
        ("testMiddleware", testMiddleware),
        ("testMiddlewareOrder", testMiddlewareOrder),
    ]
}

extension RouterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RouterTests = [
        ("testAllVoid", testAllVoid),
        ("testGetModel", testGetModel),
        ("testGetRequest", testGetRequest),
        ("testGetRequestModel", testGetRequestModel),
        ("testGetRequestURLMatch", testGetRequestURLMatch),
        ("testGetRequestURLMatchModel", testGetRequestURLMatchModel),
        ("testGetURLMatch", testGetURLMatch),
        ("testGetURLMatchModel", testGetURLMatchModel),
        ("testMethodsVoid", testMethodsVoid),
        ("testPostModel", testPostModel),
        ("testPostRequest", testPostRequest),
        ("testPostRequestModel", testPostRequestModel),
        ("testPostRequestURLMatch", testPostRequestURLMatch),
        ("testPostRequestURLMatchModel", testPostRequestURLMatchModel),
        ("testPostURLMatch", testPostURLMatch),
        ("testPostURLMatchModel", testPostURLMatchModel),
        ("testUnicodeRoute", testUnicodeRoute),
    ]
}

extension ServerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ServerTests = [
        ("testBufferSize", testBufferSize),
        ("testDescription", testDescription),
        ("testExpect", testExpect),
        ("testServer", testServer),
    ]
}

extension ThrowableRouteTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ThrowableRouteTests = [
        ("testInternalServerError", testInternalServerError),
        ("testNotFound", testNotFound),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ApplicationTests.__allTests__ApplicationTests),
        testCase(MiddlewareTests.__allTests__MiddlewareTests),
        testCase(RouterTests.__allTests__RouterTests),
        testCase(ServerTests.__allTests__ServerTests),
        testCase(ThrowableRouteTests.__allTests__ThrowableRouteTests),
    ]
}
#endif
