#if !canImport(ObjectiveC)
import XCTest

extension ClientTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ClientTests = [
        ("testDeflate", testDeflate),
        ("testGZip", testGZip),
        ("testInitializer", testInitializer),
        ("testRequest", testRequest),
        ("testURLInitializer", testURLInitializer),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ClientTests.__allTests__ClientTests),
    ]
}
#endif
