#if !canImport(ObjectiveC)
import XCTest

extension KeyValueDecoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyValueDecoderTests = [
        ("testKeyedDecoder", testKeyedDecoder),
        ("testSingleValueDecoder", testSingleValueDecoder),
    ]
}

extension KeyValueEncoderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__KeyValueEncoderTests = [
        ("testKeyedEncoder", testKeyedEncoder),
        ("testSingleValueEncoder", testSingleValueEncoder),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(KeyValueDecoderTests.__allTests__KeyValueDecoderTests),
        testCase(KeyValueEncoderTests.__allTests__KeyValueEncoderTests),
    ]
}
#endif
