#if !canImport(ObjectiveC)
import XCTest

extension BodyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BodyTests = [
        ("testRequestBytes", testRequestBytes),
        ("testRequestJSON", testRequestJSON),
        ("testRequestString", testRequestString),
        ("testResponseBytes", testResponseBytes),
        ("testResponseJSON", testResponseJSON),
        ("testResponseString", testResponseString),
    ]
}

extension ChunkedStreamTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChunkedStreamTests = [
        ("testInputStream", testInputStream),
        ("testInputStreamMultiline", testInputStreamMultiline),
        ("testOutputStream", testOutputStream),
        ("testOutputStreamMultiline", testOutputStreamMultiline),
        ("testSmallerBufferSize", testSmallerBufferSize),
    ]
}

extension HeaderNameTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HeaderNameTests = [
        ("testHeaderName", testHeaderName),
        ("testHeaderNameDescription", testHeaderNameDescription),
    ]
}

extension HeadersAuthorizationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HeadersAuthorizationTests = [
        ("testBasic", testBasic),
        ("testBearer", testBearer),
        ("testCustom", testCustom),
        ("testLowercased", testLowercased),
        ("testToken", testToken),
    ]
}

extension NginxTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NginxTests = [
        ("testChankedAllYourBase", testChankedAllYourBase),
        ("testCurlGet", testCurlGet),
        ("testFirefoxGet", testFirefoxGet),
    ]
}

extension PunycodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PunycodeTests = [
        ("testDecode", testDecode),
        ("testDecodeMixedASCII", testDecodeMixedASCII),
        ("testDecodeMixedCase", testDecodeMixedCase),
        ("testEncode", testEncode),
        ("testEncodeMixedASCII", testEncodeMixedASCII),
        ("testEncodeMixedCase", testEncodeMixedCase),
    ]
}

extension RequestDecodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RequestDecodeTests = [
        ("testAcceptCharset", testAcceptCharset),
        ("testAcceptCharsetSpaceSeparator", testAcceptCharsetSpaceSeparator),
        ("testAcceptEncodingHeader", testAcceptEncodingHeader),
        ("testAcceptHeader", testAcceptHeader),
        ("testAcceptLanguageHeader", testAcceptLanguageHeader),
        ("testAuthorization", testAuthorization),
        ("testBodyChunked", testBodyChunked),
        ("testBodyChunkedInvalidBody", testBodyChunkedInvalidBody),
        ("testBodyChunkedInvalidSizeSeparator", testBodyChunkedInvalidSizeSeparator),
        ("testBodyChunkedMissingLineEnd", testBodyChunkedMissingLineEnd),
        ("testBodyChunkedNoSizeSeparator", testBodyChunkedNoSizeSeparator),
        ("testBodyContentLength", testBodyContentLength),
        ("testContentLength", testContentLength),
        ("testContentType", testContentType),
        ("testContentTypeBoundary", testContentTypeBoundary),
        ("testContentTypeCharset", testContentTypeCharset),
        ("testContentTypeEmptyBoundary", testContentTypeEmptyBoundary),
        ("testContentTypeEmptyCharset", testContentTypeEmptyCharset),
        ("testCookies", testCookies),
        ("testCookiesJoined", testCookiesJoined),
        ("testCookiesNoSpace", testCookiesNoSpace),
        ("testCookiesTrailingSemicolon", testCookiesTrailingSemicolon),
        ("testCustomHeader", testCustomHeader),
        ("testDelete", testDelete),
        ("testEscaped", testEscaped),
        ("testExpect", testExpect),
        ("testGet", testGet),
        ("testHead", testHead),
        ("testHeaderName", testHeaderName),
        ("testHostDomainHeader", testHostDomainHeader),
        ("testHostEncodedHeader", testHostEncodedHeader),
        ("testHostHeader", testHostHeader),
        ("testInvalidEnd", testInvalidEnd),
        ("testInvalidHeaderColon", testInvalidHeaderColon),
        ("testInvalidHeaderEnd", testInvalidHeaderEnd),
        ("testInvalidHeaderName", testInvalidHeaderName),
        ("testInvalidMethod", testInvalidMethod),
        ("testInvalidRequest", testInvalidRequest),
        ("testInvalidRequest2", testInvalidRequest2),
        ("testInvalidVersion", testInvalidVersion),
        ("testInvalidVersion2", testInvalidVersion2),
        ("testInvalidVersion3", testInvalidVersion3),
        ("testInvalidVersion4", testInvalidVersion4),
        ("testKeepAliveFalse", testKeepAliveFalse),
        ("testKeepAliveTrue", testKeepAliveTrue),
        ("testPost", testPost),
        ("testPut", testPut),
        ("testTransferEncodingChunked", testTransferEncodingChunked),
        ("testTwoHeaders", testTwoHeaders),
        ("testTwoHeadersOptionalSpaces", testTwoHeadersOptionalSpaces),
        ("testUnexpectedEnd", testUnexpectedEnd),
        ("testUrl", testUrl),
        ("testUserAgentHeader", testUserAgentHeader),
        ("testVersion", testVersion),
    ]
}

extension RequestEncodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RequestEncodeTests = [
        ("testAccept", testAccept),
        ("testAcceptCharset", testAcceptCharset),
        ("testAcceptEncoding", testAcceptEncoding),
        ("testAcceptLanguage", testAcceptLanguage),
        ("testAuthorization", testAuthorization),
        ("testBodyFormURLEncodedInitializer", testBodyFormURLEncodedInitializer),
        ("testBodyJsonInitializer", testBodyJsonInitializer),
        ("testConnection", testConnection),
        ("testContentLength", testContentLength),
        ("testContentType", testContentType),
        ("testCookie", testCookie),
        ("testCustomHeaders", testCustomHeaders),
        ("testEscaped", testEscaped),
        ("testHost", testHost),
        ("testHostDomain", testHostDomain),
        ("testHostEncoded", testHostEncoded),
        ("testKeepAlive", testKeepAlive),
        ("testRequest", testRequest),
        ("testTransferEncoding", testTransferEncoding),
        ("testUrl", testUrl),
        ("testUrlQueryGet", testUrlQueryGet),
        ("testUrlQueryPost", testUrlQueryPost),
        ("testUserAgent", testUserAgent),
    ]
}

extension RequestTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RequestTests = [
        ("testDefaultMethod", testDefaultMethod),
        ("testDefaultRequest", testDefaultRequest),
        ("testDefaultURL", testDefaultURL),
        ("testFromString", testFromString),
        ("testRequest", testRequest),
    ]
}

extension ResponseDecodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResponseDecodeTests = [
        ("testBad", testBad),
        ("testBodyBytesResponse", testBodyBytesResponse),
        ("testBodyChunked", testBodyChunked),
        ("testBodyHtmlResponse", testBodyHtmlResponse),
        ("testBodyJsonResponse", testBodyJsonResponse),
        ("testBodyStringResponse", testBodyStringResponse),
        ("testBodyZeroContentLenght", testBodyZeroContentLenght),
        ("testConnection", testConnection),
        ("testContentEncoding", testContentEncoding),
        ("testContentLength", testContentLength),
        ("testContentType", testContentType),
        ("testCustomHeader", testCustomHeader),
        ("testInternalServerError", testInternalServerError),
        ("testMoved", testMoved),
        ("testNotFound", testNotFound),
        ("testOk", testOk),
        ("testSetCookie", testSetCookie),
        ("testSetCookieDomain", testSetCookieDomain),
        ("testSetCookieExpires", testSetCookieExpires),
        ("testSetCookieHttpOnly", testSetCookieHttpOnly),
        ("testSetCookieManyValues", testSetCookieManyValues),
        ("testSetCookieMaxAge", testSetCookieMaxAge),
        ("testSetCookiePath", testSetCookiePath),
        ("testSetCookieSecure", testSetCookieSecure),
        ("testTransferEncoding", testTransferEncoding),
        ("testUnauthorized", testUnauthorized),
    ]
}

extension ResponseEncodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResponseEncodeTests = [
        ("testBad", testBad),
        ("testBodyBytesResponse", testBodyBytesResponse),
        ("testBodyHtmlResponse", testBodyHtmlResponse),
        ("testBodyJsonResponse", testBodyJsonResponse),
        ("testBodyStringResponse", testBodyStringResponse),
        ("testBodyUrlFormEncodedResponse", testBodyUrlFormEncodedResponse),
        ("testConnection", testConnection),
        ("testContentEncoding", testContentEncoding),
        ("testContentType", testContentType),
        ("testCustomHeader", testCustomHeader),
        ("testInternalServerError", testInternalServerError),
        ("testMoved", testMoved),
        ("testNotFound", testNotFound),
        ("testOk", testOk),
        ("testResponseHasContentLenght", testResponseHasContentLenght),
        ("testSetCookie", testSetCookie),
        ("testSetCookieDomain", testSetCookieDomain),
        ("testSetCookieExpires", testSetCookieExpires),
        ("testSetCookieHttpOnly", testSetCookieHttpOnly),
        ("testSetCookieManyValues", testSetCookieManyValues),
        ("testSetCookieMaxAge", testSetCookieMaxAge),
        ("testSetCookiePath", testSetCookiePath),
        ("testSetCookieSecure", testSetCookieSecure),
        ("testTransferEncoding", testTransferEncoding),
        ("testUnauthorized", testUnauthorized),
    ]
}

extension ResponseTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ResponseTests = [
        ("testBytes", testBytes),
        ("testContentType", testContentType),
        ("testDefaultStatus", testDefaultStatus),
        ("testHTML", testHTML),
        ("testJavaScript", testJavaScript),
        ("testResponse", testResponse),
        ("testString", testString),
        ("testXML", testXML),
    ]
}

extension URLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__URLTests = [
        ("testAbsoluteString", testAbsoluteString),
        ("testDescription", testDescription),
        ("testFragment", testFragment),
        ("testHost", testHost),
        ("testInvalidScheme", testInvalidScheme),
        ("testPath", testPath),
        ("testQuery", testQuery),
        ("testScheme", testScheme),
        ("testUnicode", testUnicode),
        ("testURLEncoded", testURLEncoded),
    ]
}

extension UtilsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilsTests = [
        ("testDouble", testDouble),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BodyTests.__allTests__BodyTests),
        testCase(ChunkedStreamTests.__allTests__ChunkedStreamTests),
        testCase(HeaderNameTests.__allTests__HeaderNameTests),
        testCase(HeadersAuthorizationTests.__allTests__HeadersAuthorizationTests),
        testCase(NginxTests.__allTests__NginxTests),
        testCase(PunycodeTests.__allTests__PunycodeTests),
        testCase(RequestDecodeTests.__allTests__RequestDecodeTests),
        testCase(RequestEncodeTests.__allTests__RequestEncodeTests),
        testCase(RequestTests.__allTests__RequestTests),
        testCase(ResponseDecodeTests.__allTests__ResponseDecodeTests),
        testCase(ResponseEncodeTests.__allTests__ResponseEncodeTests),
        testCase(ResponseTests.__allTests__ResponseTests),
        testCase(URLTests.__allTests__URLTests),
        testCase(UtilsTests.__allTests__UtilsTests),
    ]
}
#endif
